### ISSUE TITLE
截图工具

### ISSUE THREAD

**Issue by Titanicl** [weijun-lab/region-screenshot-js#3]
请问如何关闭下方的那个截图工具？只想使用区域截图功能。

**Comment by weijun-lab** [comment]
f12看看那类名，直接display:none

**Comment by Titanicl** [comment]
已经搞定了 感谢大佬

**Comment by Titanicl** [comment]
大佬，请问每次截屏前都有允许的弹窗，感觉有些繁琐，该如何解决呢？

**Comment by weijun-lab** [comment]
这属于浏览器安全策略，没法逾越的，除非换截图的技术方案

**Comment by Titanicl** [comment]
> 这属于浏览器安全策略，没法逾越的，除非换截图的技术方案


如果打包上线后，有可靠的https协议的域名，也还是会每次截图都会有提醒的弹窗吗？还是一次允许后就不会再跳出弹窗了呢？

**Comment by weijun-lab** [comment]
每次都会有

**Comment by run210975** [comment]
截图后使用里边自带的工具添加文字，然后点击对勾后报错了，TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.
    at MockXMLHttpRequest.wt [as onreadystatechange] (region-screenshot.mjs:3921:21)
    at MockXMLHttpRequest.dispatchEvent (mock.js:8078:41)
    at XMLHttpRequest.handle (mock.js:7911:18)
